### ISSUE TITLE
Work in example, crash with implementation

### ISSUE THREAD

**Issue by sachaBlitz** [prabakarviji/OpenTok_RN#1]
Hi,

We have a probleme with the video,

When we start with your example, it is working,

But when we implement it on our app, and when we start the video, the app crash,

If you can reply, that would be really useful,

Thanks you !

**Comment by prabakarviji** [comment]
@sachaBlitz Please share your code

**Comment by prabakarviji** [comment]
@sachaBlitz It's on android or iOS?. If it's android then please check with whether you added permission to access the camera?

**Comment by sachaBlitz** [comment]
Both device : 

https://pastebin.com/4e9A4r4V : home

https://pastebin.com/m5PNp4yv : Publish

https://pastebin.com/xpwSURVS : Styles

https://pastebin.com/pXQLD2bT : Viewer

Thanks you SO much
